"""empty message

Revision ID: 29e0e11f380a
Revises: 4cb532fedcf8
Create Date: 2019-08-07 11:52:58.417691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e0e11f380a'
down_revision = '4cb532fedcf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('article_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'articles', ['article_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'article_id')
    # ### end Alembic commands ###
