"""empty message

Revision ID: 97db95a71bca
Revises: 445224223be7
Create Date: 2019-08-05 19:06:57.593111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97db95a71bca'
down_revision = '445224223be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_categories_rls',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['article_categories.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'category_id')
    )
    op.add_column('article_tags', sa.Column('article', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'article_tags', 'articles', ['article'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article_tags', type_='foreignkey')
    op.drop_column('article_tags', 'article')
    op.drop_table('article_categories_rls')
    # ### end Alembic commands ###
