"""empty message

Revision ID: dbf9dbed0991
Revises: af5879039aab
Create Date: 2019-08-05 16:03:36.768045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf9dbed0991'
down_revision = 'af5879039aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile', sa.String(length=20), nullable=False))
    op.drop_index('password', table_name='users')
    op.create_unique_constraint(None, 'users', ['mobile'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('password', 'users', ['password'], unique=True)
    op.drop_column('users', 'mobile')
    # ### end Alembic commands ###
